### ISSUE TITLE
Content removal ahead of time

### ISSUE THREAD

**Issue by dakiesse** [sweetalert2/sweetalert2-react-content#106]
https://github.com/sweetalert2/sweetalert2-react-content/blob/ec05a41dc1d11ac0b42a7b1585cdb1ae5c704a10/src/index.js#L45

why not .onAfterClose? Unmounting happens before closing now and you can see jerking when the closing.

**Comment by zenflow** [comment]
The most likely reason for this is simply that onAfterClose did not exist at the time this package was originally drafted
- initial commit in this repo in February 2018 https://github.com/sweetalert2/sweetalert2-react-content/commit/f9af0c880ac9f08a4dc00c58b0fbb0d2d5c79e3d
- onAfterClose added in sweetalert2 in March 2018 https://github.com/sweetalert2/sweetalert2/pull/1030

**Comment by dakiesse** [comment]
@zenflow will it be changed?

**Comment by zenflow** [comment]
I think we should change it, but not to onAfterClose.. After a little experimentation, I found that neither onClose nor onAfterClose are ideal, since neither are called when the current modal is interrupted by another modal. 

Example: A modal is opened, and before it is closed, another modal opens. The onClose & onAfterClose methods will never be called for the first modal.

This scenario is not typical, but is possible, and probably happens in some apps.

In this scenario, the result is memory leaks and the possibly bugs (if the mounted react component has some activity based on timers, network, etc.).

I think we should implement some new callback option(s) in the sweetalert2 package, where it's possible to implement "cleanup" code which we can rely on being called. For example, `onDestroy` (which would be called when the modal's life is over, regardless of if it was interrupted, or actually closed), or `onUnRender` (which would be called to clean up from every rendering). If we implemented `onUnRender` then here we could use `onRender` and `onUnRender` and easily take care of #73 at the same time.

/cc @limonte

**Comment by limonte** [comment]
> I think we should implement some new callback option(s) in the sweetalert2 package, where it's possible to implement "cleanup" code which we can rely on being called. For example, `onDestroy` (which would be called when the modal's life is over, regardless of if it was interrupted, or actually closed), or `onUnRender` (which would be called to clean up from every rendering). If we implemented `onUnRender` then here we could use `onRender` and `onUnRender` and easily take care of #73 at the same time.
> 
> /cc @limonte

Sounds like a great idea, but I don't know how to implement it :man_shrugging: Let's take this simple code:

```js
Swal.fire('one')
Swal.fire('two')
```

Here `Swal.fire('two')` will dispose the first modal. In other words the first modal doesn't dispose itself, but another instance [cleaning up DOM tree](https://github.com/sweetalert2/sweetalert2/blob/master/src/utils/dom/init.js#L47) before rendering itself. In `resetOldContainer()` function, the second modal knows nothing about the params of the first one.

**Comment by zenflow** [comment]
@limonte I think we would need to:
1. Store the current Swal instance in the global state (e.g. `globalState.currentInstance`)
2. Add a `swal._destroy()` instance method that can take care of cleanup, including calling the user-provided `onDestroy` callback
3. Near the start of the `swal._main` method:
```
if (globalState.currentInstance) {
  globalState.currentInstance._destroy()
}
globalState.currentInstance = this
```

@gverni Would love to get your thoughts on all of this

**Comment by limonte** [comment]
Thank you for the suggestion @zenflow The related PR is ready for your review: https://github.com/sweetalert2/sweetalert2/pull/1872
