### ISSUE TITLE
Swal.fire method signature problem on Typescript 3.9.5

### ISSUE THREAD

**Issue by ramazanyigit** [sweetalert2/sweetalert2-react-content#114]
```tsx
import React from "react";
import Swal from "sweetalert2";
import withReactContent from "sweetalert2-react-content";

const MySwal = withReactContent(Swal)

MySwal.fire({
  title: <p>Hello World</p>,
  footer: 'Copyright 2018',
  onOpen: () => {
    // `MySwal` is a subclass of `Swal`
    //   with all the same instance & static methods
    MySwal.clickConfirm()
  }
}).then(() => {
  return MySwal.fire(<p>Shorthand works too</p>)
})
```

In the example above, the `MySwal.fire` method gives the error below on Typescript 3.9.5
```
Types of property 'title' are incompatible.
        Type 'ReactElementOr<"title">' is not assignable to type 'string | HTMLElement | JQuery<HTMLElement> | 
undefined'.
```

The typescript definition file not correctly mimics the SweetAlert2's call signatures.

```tsx
/// Wrong definition
interface ReactSweetAlert {
  (title?: ReactElementOr<'title'>, message?: ReactElementOr<'html'>, icon?: SweetAlertIcon): Promise<SweetAlertResult>;

  (options: ReactSweetAlertOptions & { useRejections?: false }): Promise<SweetAlertResult>;

  (options: ReactSweetAlertOptions & { useRejections: true }): Promise<any>;
}

/// Correct definition
interface ReactSweetAlert {
  fire(title?: ReactElementOr<'title'>, message?: ReactElementOr<'html'>, icon?: SweetAlertIcon): Promise<SweetAlertResult>;

  fire(options: ReactSweetAlertOptions & { useRejections?: false }): Promise<SweetAlertResult>;

  fire(options: ReactSweetAlertOptions & { useRejections: true }): Promise<any>;
}
```
If the ReactSweetAlert definition is updated with the second one, the error is resolved.

**Comment by zenflow** [comment]
This fix could be a problem for other users, since, although it's not in documentation anymore, `Swal` (and by extension, `MySwal`) can be instantiated without the static `fire` method. It can also be instantiated with `new MySwal(...sameArgsAsFire)`. See https://github.com/sweetalert2/sweetalert2/issues/1438 if you are wondering why we use `Swal.fire`. 

If you like, you can update your fix to reflect that, and submit it in a PR so that once it is merged you are shown as a contributor to the project.  You can make the edit and submit the PR from your web browser: https://github.com/sweetalert2/sweetalert2-react-content/edit/master/src/sweetalert2-react-content.d.ts

Otherwise, your contribution is still very much valued. Thanks @ramazanyigit!

**Comment by ramazanyigit** [comment]
@zenflow thanks for your fast response. I created the PR and linked to the issue.
