### ISSUE TITLE
Release v1.0.0

### ISSUE THREAD

**Issue by zenflow** [sweetalert2/sweetalert2-react-content#12]
I just want to give the sweetalert2 collaborators a chance to review. https://github.com/sweetalert2/sweetalert2/pull/1000#issuecomment-371223562

Add some more package keywords to make this more discoverable.

Then I'll make the first major release.

**Comment by toverux** [comment]
Well, it looks quite good to me :)

I've had a quick glance at it and the packed archive and the code looks good - I'll trust you on the rest. So, what's good:

- [x] tests
- [x] built artifacts and archive structure
- [x] usefulness of this integration (worth to mention in that jungle of integrations, lol)
- [x] simple n' lean, react way
- [x] *peer* dep on sweetalert2
- [x] release process

What can be improved (now or in a future version):

 - [ ] missing non-minified builds in ES5 or ES Next and their source maps, with import/export (as modern bundlers like them).
   I recommend you to have a look at ngx-sweetalert2's packed archive (the informations and artifacts are not present on the source control and are generated in the release process, you have to install it), it has everything you need (types, ESM+ES5, ESM+ES2015, UMD, minified UMD, source maps)
 - [ ] (more important) The package.json has a `jsnext:main` that points to a non-module, minified file. Also, [jsnext:main has been deprecated a long time ago with `module`](https://github.com/jsforum/jsforum/issues/5). Remove the `jsnext:main` entry or replace it with a `module` entry that actually points to an ES 2015 module.
 - [ ] The readme is a bit poor, altough sufficient (I mean, you can improve the "design", etc)

Good job!

**Comment by limonte** [comment]
> I heard many times that React and TypeScript were now good friends [...] Would you like me to provide them?

At least, I would like that a lot :)

**Comment by zenflow** [comment]
@toverux Thank you *so* much for all the comments! This definitely helps!

I read you loud on clear on the first two points. I'll look into this and post here when I think I've fixed it.

> The readme is a bit poor, altough sufficient (I mean, you can improve the "design", etc)

What do you mean by the "design"? Like, the organization of sections? On a side-note I kinda like that it is short and sweet, yet includes all the info that is of use. Less is more. 

> No TypeScript declaration. [...] Would you like me to provide them?

Absolutely! I haven't invested the time into learning TypeScript language and tooling, but I know it is something useful, and I want to support it. Please please, go ahead and provide the TypeScript declaration.

**Comment by zenflow** [comment]
@toverux 

> missing non-minified builds in ES5 or ES Next and their source maps

I've thought about it more and come up with questions. Is the non-minified build necessary when you have a source map for the minified build (as this package does)? If so, what is it's use case? In the past I could see it being useful for debugging, but now we're in the future with source maps that work with bundlers and browsers right?

> with import/export (as modern bundlers like them).

Can you give me an explanation or reference? It seems like modern bundlers are ok with UMD.. and so is node.js obviously since UMD works in CJS environments. If that's right then I can save a lot of overhead in complexity and kilobytes.

**Comment by toverux** [comment]
> Is the non-minified build necessary when you have a source map for the minified build (as this package does)?

Not _necessary_, indeed, but still useful in various scenarios:
 - The user wants to apply it's own minification settings (and quite often, the minification happens two times: when the maintener builds it and then, in the user build setup).
 - Bad source maps setup (in that case, having a non-minified build in development is useful)
 - Debugging of vendors. Sometimes I want to change a vendor source by hand to see what's happening or find a bug and there's nothing more practical than a non-minified build _by default_.

If you look at modern frontend packages, more and more of them have a non-minified UMD file as the `main` entry. I'd even say that it is a community convention today.
Sometimes `.min.js` files are not even provided, and when they are generated, that's mainly for CDNs or by habit.
SweetAlert2 also has its non-minified build as the `main` entry: https://github.com/sweetalert2/sweetalert2/blob/master/package.json#L7

> It seems like modern bundlers are ok with UMD.. and so is node.js obviously since UMD works in CJS environments.

ES modules have the great advantage of being statically analizable, while UMD is more of a compatibility layer that acts at runtime (even if modern bundlers are smart enough to parse them).

But UMD still have to export the whole library. With ESM, your module bundler can take only what you are actually using (tree shaking, unused code elimination), reducing the size of the final bundle. Module bundlers can also flatten your module, reducing the final output again.

You project will not benefit a lot from it since you're only exporting one symbol. But still, it's cleaner and like I said, bundlers prefer them by default since it allows better, static linking, may avoid the need to wrap the module in the final user bundle, and the bundler don't have to guess about the UMD module ID.

UMD is the past. It's the most portable thing and was a community success towards interoperability, and that's why we still use it as the fallback solution or in legacy projects. But ESM is a new language-level feature, it's cleaner, more flexible, and statically analyzable. It seems to be a must have now :)

**Comment by zenflow** [comment]
> (more important) The package.json has a jsnext:main that points to a non-module, minified file. Also, jsnext:main has been deprecated a long time ago with module. Remove the jsnext:main entry or replace it with a module entry that actually points to an ES 2015 module.

Done in 18ed0d79a7063b2983bceb20058c0dc268bb8889 and released in 0.3.0

**Comment by zenflow** [comment]
> The readme is a bit poor, altough sufficient (I mean, you can improve the "design", etc)

@toverux sorry, could you describe a little more what you think could be improved? I'm not sure what you mean. Thanks!

**Comment by zenflow** [comment]
#14 has actually led to blocking the release and making me consider renaming this project to sweetalert2-mixin-react lol

**Comment by zenflow** [comment]
addressed most of @toverux's concerns and 1.0.0 is out, so closing this.

@toverux please leave any specific notes about the README here and I'll address them too
