### ISSUE TITLE
React element not working for html property

### ISSUE THREAD

**Issue by hhoangg** [sweetalert2/sweetalert2-react-content#239]
```ts
const confirm = (option: SweetAlertOptions<void, any>, action: () => void) => {
    return MySwal.fire({
      title: 'Are you sure?',
      text: "You won't be able to revert this!",
      icon: 'warning',
      showCancelButton: true,
      confirmButtonText: 'Yes, delete it!',
      showLoaderOnConfirm: true,
      allowOutsideClick: false,
      preConfirm: action,
      ...option,
    }).then((result) => {
      if (result.isConfirmed) {
        MySwal.fire('Deleted!', 'Your file has been deleted.', 'success')
      }
    })
  }
```
I created a function like above, but when I pass the property `html` in it doesn't work properly, instead it shows as `[object Object]`
<img width="290" alt="image" src="https://user-images.githubusercontent.com/19337273/227103488-ffd152bd-b2e6-4d73-8fae-773f5168a2bd.png">

can you tell me where i am wrong? please.

**Comment by zenflow** [comment]
Not enough info here. This doesn't tell me what you're passing for `html`.

Please fork this sandbox to provide a reproduction: https://codesandbox.io/s/sweetalert2-react-content-sandbox-6mri0o
I'll see if I can help.

As you can see in the sandbox though, the `html` property seems to be working alright.

**Comment by hhoangg** [comment]
I'm sorry, my mistake
sandbox [here](https://codesandbox.io/p/sandbox/misty-surf-pxthn1?file=%2Fsrc%2FApp.tsx)

The source on the Codesandbox is perfect work, but the source on my local is not working

Here is the error message

<img width="456" alt="image" src="https://user-images.githubusercontent.com/19337273/227148411-7b87c86b-813c-418b-96f8-f3fbc255676d.png">

**Comment by zenflow** [comment]
@hhoangg You're using the wrong type for options.
Import `ReactSweetAlertOptions` from "sweetalert2-react-content" and use that instead.
The type error is a different issue though since types don't affect runtime behavior.

As you said, the sandbox doesn't reproduce your original issue.
I can't really help with that issue unless we have a reproduction.
I suggest work on reproducing the issue, by adding to the sandbox step by step, until one step brings out the issue, and then you will probably know what your issue is and you probably won't need any help

**Comment by hhoangg** [comment]
> Import `ReactSweetAlertOptions` from "sweetalert2-react-content" and use that instead.

This change solved my problem.
But I wonder why on Codesandbox I don't use that `type` but don't get errors like below my source.
But anyway this answer solved my problem, thank you for taking some time to help me
