### ISSUE TITLE
Property 'fire' does not exist on type 'typeof swal & ReactSweetAlert'.

### ISSUE THREAD

**Issue by lexcorp16** [sweetalert2/sweetalert2-react-content#33]
Following the sample exactly as it exists in the ReadMe, I get the following error saying `'fire' does not exist on type 'typeof swal & ReactSweetAlert'.` and taking a look at `sweetalert2.d.ts`, 'fire' indeed does not exist.

**Comment by limonte** [comment]
Related to https://github.com/sweetalert2/sweetalert2/issues/1075

**Comment by zenflow** [comment]
The typings file wasn't updated with the js code in sweetalert2 when that method was added (my bad). I will do that.

@lexcorp with TypeScript is it possible to disable type checking in certain places? Something similar to `/* eslint-disable-line */`? If you can do that or otherwise disable type checking here it should work fine

**Comment by zenflow** [comment]
There are two options for a workaround until this is fixed:

1. Don't use `MySwal.fire(...args)`. Instead use `new MySwal(...args)`. These are equivalent.
2. If you are doing nothing with the return value, the 1st workaround would cause a ["no-new" lint error](https://eslint.org/docs/rules/no-new), so use `(MySwal as any).fire(...args)`. I suggest also leaving a comment referring to this issue.

**Comment by zenflow** [comment]
https://github.com/sweetalert2/sweetalert2-react-content/issues/69#issuecomment-463138505:
> As I understand correctly, #33 will be resolved automatically by resolving #66
