### ISSUE TITLE
Unit testing in Jest Enzyme

### ISSUE THREAD

**Issue by mshez** [sweetalert2/sweetalert2-react-content#65]
First of all great library. I have used MySwal.fire in function here:
```
MySwal.fire({
      title: 'Warning',
      text: 'Are you sure you want to close this request ?',
      type: 'question',
      showCancelButton: true
    }).then((result)=>{
if(result.value){
//My logic after pressed OK
}
}
```

Now i am writing a unit test for it. Here is some of test i have been doing
```
const wrapper = mount(
      <Router>
        <I18nextProvider i18n={i18n}>
          <SearchRequests />
        </I18nextProvider>
      </Router>

    const closeButton = wrapper.find('table').find('button');
    // window.confirm = jest.fn(() => true);
    closeButton.simulate('click');
    )
```

As you can see here before i was using window.confirm. How can i mock Swal.fire to return true so that my further logic works in unit test

**Comment by zenflow** [comment]
Sorry @mshez, I will close this because it's more of a "how do I mock a method using Jest Enzyme?" question rather than an issue with this package. Try StackOverflow. FYI I would have offered some tips before closing if you had provided a reduced but sufficient version of your test (and without syntax errors).
