### ISSUE TITLE
Render jsx elements and components not working

### ISSUE THREAD

**Issue by devedupereira** [sweetalert2/sweetalert2-react-content#67]
Hi all,

I'm trying to render some React content inside SweetAlert and it's not working properly:

```handleDetails = () => {
    const mySwal = withReactContent(swal);
    mySwal.fire({
      title: 'Product settings',
      html: (
        <Fragment>
          <p>
            My product settings
          </p>
          <Settings />
        </Fragment>)
    });
  }```

How can I render this "html" inside swal?

**Comment by zenflow** [comment]
It is usually helpful to answer this question in an issue report: What happens when you run your code? Do you get an error in the browser console? What happens visually?

The code looks fine, as long as you are properly transpiling your jsx to js, and `Fragment` and `Settings` are imported or defined in scope (did you leave that part of the code out of your provided sample? or are you getting a ReferenceError?)

Please ensure you have `sweetalert2@^7.18.0` installed; this package is not yet compatible with the recently released sweetalert2 version 8.

If the above tip doesn't solve the problem, try to reproduce on a "code playground" site, like https://codesandbox.io/ or  https://codepen.io/ or another.

**Comment by devedupereira** [comment]
Here's a full example of issue: https://codesandbox.io/s/1y15k1j5y7

**Comment by devedupereira** [comment]
All packages are with my own version, and I get exactly same problem reproduced on codesandbox, just not render content visually.

**Comment by zenflow** [comment]
I advise you to check browser console for errors or warnings when troubleshooting unexpected behavior..

Here is what you see in the browser console after clicking the "click me" button:

![image](https://user-images.githubusercontent.com/3198597/51865272-f22bca00-232c-11e9-819c-88eec9967830.png)

So the problem has nothing to do with this package.. you need to add `import React from "react";` to the top of your `settings.jsx`
