### ISSUE TITLE
Render a redux connected component as content

### ISSUE THREAD

**Issue by filippoitaliano** [sweetalert2/sweetalert2-react-content#96]
In my app, I have generic components that have the responsibility to encapsulate the interface and the data handling about specific entities. Any time I need to use them, they are good to go and connected to Redux to retrieve related global data. I cannot use them within a Swal for the following reason. The internal implementation uses `ReactDOM.render` to render the component in the Sweetalert content node. The problem is that rendering a new tree prevents the children to access parent's contexts like the react-redux one.

To be exhaustive, before realizing the real point I changed the target root of the Swal to be inside the react-redux Provider.

```jsx
const App = ({ store }) => (
  <Provider store={store}>
      <div id="swal-root" />  {/* < specified root */}
        ...
```

After that, I got the problem was not only the node location but also the internal implementation.

It's possible to support somehow this usage? Do you have any idea about using Redux inside the Swal content?

Thank you for your awesome work!

**Comment by zenflow** [comment]
Changing the target root of the Swal to be inside the Provider will not work because the Swal will only be rendered in the DOM, not in the React component/element tree, which (although not possible) is what would be needed for the React content you pass to Swal to get the parent context.

Simple solution here I think is to use the `<Provider store={store}>` in your Swal content to create another context using the same `store`. 

For example, if you currently are calling Swal like this:

```
MySwal.fire(<MyComponentUsingRedux/>)
```

Change it to this:

```
MySwal.fire(<Provider store={store}><MyComponentUsingRedux/></Provider>)
```
